# Generated by Django 3.1.6 on 2021-02-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='id_coutry',
            new_name='id_state',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='id_coutry',
            new_name='id_city',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('cep', models.CharField(max_length=10)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city')),
            ],
        ),
    ]
